version: '3.8'

services:
  se_489_mlops_project:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: se_489_mlops_project_app
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
