site_name: SE 489 MLOps Project
site_description: "Predict SLA violations from event sequences"
site_author: "Ted Strall"
docs_dir: .
site_dir: ../site
exclude_docs: README.md

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: api.md
  - Phase 1: PHASE1.md
  - Phase 2: PHASE2.md
  - Phase 3: PHASE3.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc
